apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}" 
    visualize: "true" 
    app: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector: 
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true" 
    spec:
      containers: 
      - name: {{ .Chart.Name }} 
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}" 
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: 
        - name: POST_ADDRESS
          value: "cms-notifier:8080"
        - name: BUCKET_ADDRESS
          valueFrom: 
            configMapKeyRef: 
              name: global-config 
              key: aws.s3.image.binaries.bucket
        - name: TEST_UUID
          value: "6a70679a-fd9b-4d64-9bec-2d340fb75021"
        ports: 
        - containerPort: 8080 
        livenessProbe: 
          tcpSocket: 
            port: 8080 
          initialDelaySeconds: 10 
        readinessProbe: 
          httpGet: 
            path: "/__gtg" 
            port: 8080 
          initialDelaySeconds: 15 
          periodSeconds: 30 
        resources: 
{{ toYaml .Values.resources | indent 12 }}

